In [1]:
import numpy as np

A = np.arange(6).reshape(3,2)
B = np.arange(8).reshape(2,4)
C = np.dot(A,B)
# print(A,'\n\n',B,'\n\n',C)

print(C)
print(C.max())

[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]
47
